{{ config(materialized='view') }}

select
  day                                as date,
  app,
  app_token,
  store_id,
  store_type,
  network,
  campaign,
  campaign_id_network                as campaign_id,
  adgroup,
  adgroup_id_network                 as adgroup_id,
  source_network                     as source,
  source_id_network                  as source_id,
  creative,
  creative_id_network                as creative_id,
  upper(coalesce(country_code, ''))  as country,
  region,
  lower(coalesce(os_name, ''))       as platform,
  device_type,
  channel,
  partner_name,
  partner_id,

  installs,
  network_installs,
  organic_installs,
  non_organic_installs,
  reinstalls,
  first_reinstalls,
  reattributions,
  reattribution_reinstalls,
  uninstalls,
  first_uninstalls,
  uninstall_cohort,
  sessions,
  base_sessions,
  daus,
  waus,
  maus,
  clicks,
  attribution_clicks,
  network_clicks,
  impressions,
  attribution_impressions,
  network_impressions,
  events,
  revenue_events,
  paid_clicks,
  paid_impressions,
  paid_installs,
  ad_impressions,

  cost,
  adjust_cost,
  network_cost,
  ecpi,
  ecpi_all,
  network_ecpi,
  ecpc,
  ecpm,
  network_ecpm,
  click_cost,
  impression_cost,
  install_cost,
  revenue,
  cohort_revenue,
  all_revenue,
  ad_revenue,
  ad_rpm,
  arpdau,
  arpdau_ad,
  arpdau_iap,
  gross_profit,
  return_on_investment,
  revenue_to_cost,
  roas,
  roas_ad,
  roas_iap,
  click_conversion_rate,
  ctr,
  impression_conversion_rate,

  -- Organic if no paid spend recorded; useful for marts that split paid vs organic.
  coalesce(cost, 0) > 0              as is_paid

from {{ source('adjust', 'adjust_report') }}
